#!/usr/bin/env zsh
# vi: set expandtab ft=zsh tw=80 ts=2

function getPrefDir() {
	local osName="`uname -s`"
	eval "`docopts -f -V - -h - : "$@" <<- USAGE
	Usage:
	  $0 [options] <appname>
	  $0 [options] <appname> appdata

	Get the system specific directory for storing preferences and configuration
	files. Currently supports only macOS.

	Options:
	  -o OSNAME, --os=OSNAME   The operating system. Either Linux or Darwin. [default: ${osName}]
	----
	$0 0.1.0
	Copyright (C) 2022 Rezart Qelibari, Astzweig GmbH & Co. KG
	License EUPL-1.2. There is NO WARRANTY, to the extent permitted by law.
	USAGE`"
	local prefDir
	if [ "${os:l}" = 'darwin' ]; then
		prefDir="${HOME}/Library/Preferences"
		[ "${appdata}" = 'true' ] && prefDir="${HOME}/Library/Application Support/${appname}"
	else
		prefDir="${HOME}"
		[ "${appdata}" = 'true' ] && prefDir="${HOME}/.${appname}"
	fi
	echo "${prefDir}"
}

if [[ "${ZSH_EVAL_CONTEXT}" == toplevel || "${ZSH_EVAL_CONTEXT}" == *loadautofunc ]]; then
	getPrefDir "$@"
fi
