#!/usr/bin/env zsh
# vi: set expandtab ft=zsh tw=80 ts=2

function trim() {
  eval "`docopts -f -V - -h - : "$@" <<- USAGE
	Usage: $0 [<str>]
	
	Output the given string with leading and trailing whitespace removed.
	----
	$0 0.1.0
	Copyright (C) 2022 Rezart Qelibari, Astzweig GmbH & Co. KG
	License EUPL-1.2. There is NO WARRANTY, to the extent permitted by law.
	USAGE`"
  str="${str/#[[:space:]]/}"
  str="${str/%[[:space:]]/}"
  print -- "${str}"
}

if [[ "${ZSH_EVAL_CONTEXT}" == toplevel || "${ZSH_EVAL_CONTEXT}" == *loadautofunc ]]; then
  trim "$@"
fi
